# Generated by Django 5.2.8 on 2025-12-14 05:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("timetable", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Announcement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Tekst")),
                (
                    "pdf_file",
                    models.FileField(
                        upload_to="announcements_pdfs/", verbose_name="PDF faýl"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Bildiriş",
                "verbose_name_plural": "Bildirişler",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="course",
            options={"verbose_name_plural": "Kurs"},
        ),
        migrations.AlterModelOptions(
            name="day",
            options={"ordering": ["number"], "verbose_name_plural": "Gün"},
        ),
        migrations.AlterModelOptions(
            name="faculty",
            options={"verbose_name_plural": "Fakultet"},
        ),
        migrations.AlterModelOptions(
            name="group",
            options={"verbose_name_plural": "Topar"},
        ),
        migrations.AlterModelOptions(
            name="lessonnumber",
            options={"verbose_name_plural": "Sapak nomer"},
        ),
        migrations.AlterModelOptions(
            name="lessontype",
            options={"verbose_name_plural": "Sapak görnüşi"},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"verbose_name_plural": "Sapaklaryň ady"},
        ),
        migrations.AlterModelOptions(
            name="teacher",
            options={"verbose_name_plural": "Mugallym"},
        ),
        migrations.AlterModelOptions(
            name="timetableentry",
            options={
                "ordering": ["week__number", "day__number", "lesson_number__number"],
                "verbose_name_plural": "Sapak tertibi",
            },
        ),
        migrations.AlterModelOptions(
            name="week",
            options={"verbose_name_plural": "Hepde"},
        ),
    ]
