# Generated by Django 5.2.8 on 2025-12-14 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "timetable",
            "0002_announcement_alter_course_options_alter_day_options_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Subgroup",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(choices=[("A", "A"), ("B", "B")], max_length=1),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subgroups",
                        to="timetable.group",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Podtopar",
                "unique_together": {("name", "group")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="timetableentry",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="timetableentry",
            name="subgroup",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="timetable.subgroup",
            ),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name="timetableentry",
            unique_together={("week", "day", "subgroup", "lesson_number")},
        ),
        migrations.RemoveField(
            model_name="timetableentry",
            name="group",
        ),
    ]
