# Generated by Django 5.2.8 on 2025-12-14 13:43

import django.db.models.deletion
import smart_selects.db_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetable', '0003_subgroup_alter_timetableentry_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='course',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='faculty', chained_model_field='faculty', null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.course', verbose_name='Kurs'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.faculty', verbose_name='Fakultet'),
        ),
        migrations.AddField(
            model_name='timetableentry',
            name='group',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='course', chained_model_field='course', null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.group', verbose_name='Topar'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='subgroup',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, blank=True, chained_field='group', chained_model_field='group', null=True, on_delete=django.db.models.deletion.PROTECT, to='timetable.subgroup', verbose_name='Podtopar'),
        ),
    ]
